spring:
  application:
    name: careslot

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:<PORT>/careslot}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}

careslot:
  holds:
    expiry-batch-size: 100